// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwD1Wl5FbkOjC8YvuI1S5KmHH5e1PMtoo',
    appId: '1:454112524139:web:e5571e68faecc03d10fe2e',
    messagingSenderId: '454112524139',
    projectId: 'kopma-tels',
    authDomain: 'kopma-tels.firebaseapp.com',
    storageBucket: 'kopma-tels.firebasestorage.app',
    measurementId: 'G-WSYQQCFHVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzc2p6A84HpMbgHmIfOKnmnt2_ovMpjgk',
    appId: '1:454112524139:android:e4ad4a60973b199c10fe2e',
    messagingSenderId: '454112524139',
    projectId: 'kopma-tels',
    storageBucket: 'kopma-tels.firebasestorage.app',
  );
}
